2020-09-25 16:46:22,142 ERROR 14172 [-/127.0.0.1/-/3ms POST /register] nodejs.TypeError: Cannot read property 'filepath' of undefined
    at UserController.register (C:\Users\HASEE\桌面\mycake\cake\server\app\controller\user.js:11:60)
    at Object.callFn (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\koa-compose\index.js:45:18)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\koa-compose\index.js:44:32)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:46:55,093 ERROR 14172 [-/127.0.0.1/-/110ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","","http://127.0.0.1:7001/public/upload/5085ce0f-4a2d-4d51-aeef-e1183df57870.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"\",\"http://127.0.0.1:7001/public/upload/5085ce0f-4a2d-4d51-aeef-e1183df57870.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:08,841 ERROR 14172 [-/127.0.0.1/-/8ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/7d8b9e7c-b698-48bd-a442-b98d08838253.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/7d8b9e7c-b698-48bd-a442-b98d08838253.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:10,803 ERROR 14172 [-/127.0.0.1/-/9ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/c35b67b5-bd8f-4835-b9ac-9eb97f57f78c.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/c35b67b5-bd8f-4835-b9ac-9eb97f57f78c.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:11,441 ERROR 14172 [-/127.0.0.1/-/8ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/9e305caa-6f3f-4195-9e26-f2d24ee59b2e.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/9e305caa-6f3f-4195-9e26-f2d24ee59b2e.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:11,674 ERROR 14172 [-/127.0.0.1/-/8ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/300b1d33-46f0-4015-be7d-6413171c816b.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/300b1d33-46f0-4015-be7d-6413171c816b.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:11,879 ERROR 14172 [-/127.0.0.1/-/7ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/0d704a07-2dd9-45f0-8a00-f5a40f0819c0.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/0d704a07-2dd9-45f0-8a00-f5a40f0819c0.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:12,038 ERROR 14172 [-/127.0.0.1/-/7ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/4b6ab8a7-84ea-4be9-84e8-3aa83dad8510.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/4b6ab8a7-84ea-4be9-84e8-3aa83dad8510.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:12,640 ERROR 14172 [-/127.0.0.1/-/10ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/ed8f246f-48a1-4799-9b84-f1257df24604.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/ed8f246f-48a1-4799-9b84-f1257df24604.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:12,828 ERROR 14172 [-/127.0.0.1/-/8ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/cd1d6f5f-0a48-4c8d-8223-1dec4d3aee3e.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/cd1d6f5f-0a48-4c8d-8223-1dec4d3aee3e.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:13,094 ERROR 14172 [-/127.0.0.1/-/8ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/d1b6694a-64e1-4702-9f78-f7827663c65e.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/d1b6694a-64e1-4702-9f78-f7827663c65e.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:13,318 ERROR 14172 [-/127.0.0.1/-/9ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/41de0ccb-c262-4923-8da5-4db42387abac.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/41de0ccb-c262-4923-8da5-4db42387abac.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-26 23:35:45,874 ERROR 4328 [-/127.0.0.1/-/3ms GET /car] nodejs.TypeError: Cannot read property 'Uid' of undefined
    at CarService.car (C:\Users\12552\Desktop\mycake\cake\server\app\service\car.js:7:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async UserController.car (C:\Users\12552\Desktop\mycake\cake\server\app\controller\car.js:7:20)
    at async C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\12552\Desktop\mycake\cake\server\node_modules\koa-session\index.js:41:7)
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8081","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 4328
hostname: DESKTOP-K5ULKD4

2020-09-26 23:35:49,709 ERROR 4328 [-/127.0.0.1/-/2ms GET /car] nodejs.TypeError: Cannot read property 'Uid' of undefined
    at CarService.car (C:\Users\12552\Desktop\mycake\cake\server\app\service\car.js:7:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async UserController.car (C:\Users\12552\Desktop\mycake\cake\server\app\controller\car.js:7:20)
    at async C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\12552\Desktop\mycake\cake\server\node_modules\koa-session\index.js:41:7)
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8081","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 4328
hostname: DESKTOP-K5ULKD4

