2020-09-25 16:46:22,141 ERROR 14172 [-/127.0.0.1/-/3ms POST /register] nodejs.TypeError: Cannot read property 'filepath' of undefined
    at UserController.register (C:\Users\HASEE\桌面\mycake\cake\server\app\controller\user.js:11:60)
    at Object.callFn (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\koa-compose\index.js:45:18)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\koa-compose\index.js:44:32)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:46:55,091 ERROR 14172 [-/127.0.0.1/-/110ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","","http://127.0.0.1:7001/public/upload/5085ce0f-4a2d-4d51-aeef-e1183df57870.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"\",\"http://127.0.0.1:7001/public/upload/5085ce0f-4a2d-4d51-aeef-e1183df57870.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:08,837 ERROR 14172 [-/127.0.0.1/-/8ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/7d8b9e7c-b698-48bd-a442-b98d08838253.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/7d8b9e7c-b698-48bd-a442-b98d08838253.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:10,800 ERROR 14172 [-/127.0.0.1/-/9ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/c35b67b5-bd8f-4835-b9ac-9eb97f57f78c.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/c35b67b5-bd8f-4835-b9ac-9eb97f57f78c.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:11,438 ERROR 14172 [-/127.0.0.1/-/8ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/9e305caa-6f3f-4195-9e26-f2d24ee59b2e.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/9e305caa-6f3f-4195-9e26-f2d24ee59b2e.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:11,671 ERROR 14172 [-/127.0.0.1/-/8ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/300b1d33-46f0-4015-be7d-6413171c816b.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/300b1d33-46f0-4015-be7d-6413171c816b.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:11,877 ERROR 14172 [-/127.0.0.1/-/7ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/0d704a07-2dd9-45f0-8a00-f5a40f0819c0.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/0d704a07-2dd9-45f0-8a00-f5a40f0819c0.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:12,035 ERROR 14172 [-/127.0.0.1/-/7ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/4b6ab8a7-84ea-4be9-84e8-3aa83dad8510.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/4b6ab8a7-84ea-4be9-84e8-3aa83dad8510.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:12,637 ERROR 14172 [-/127.0.0.1/-/10ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/ed8f246f-48a1-4799-9b84-f1257df24604.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/ed8f246f-48a1-4799-9b84-f1257df24604.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:12,826 ERROR 14172 [-/127.0.0.1/-/8ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/cd1d6f5f-0a48-4c8d-8223-1dec4d3aee3e.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/cd1d6f5f-0a48-4c8d-8223-1dec4d3aee3e.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:13,091 ERROR 14172 [-/127.0.0.1/-/8ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/d1b6694a-64e1-4702-9f78-f7827663c65e.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/d1b6694a-64e1-4702-9f78-f7827663c65e.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-25 16:47:13,316 ERROR 14172 [-/127.0.0.1/-/9ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'img' in 'field list'
    at Query.Sequence._packetToError (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Pool.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\HASEE\桌面\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into user (phone,pwd,birth,img) values ("15122223333","a123456","2019-12-30","http://127.0.0.1:7001/public/upload/41de0ccb-c262-4923-8da5-4db42387abac.jpg")
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'img' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user (phone,pwd,birth,img) values (\"15122223333\",\"a123456\",\"2019-12-30\",\"http://127.0.0.1:7001/public/upload/41de0ccb-c262-4923-8da5-4db42387abac.jpg\")"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8080","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14172
hostname: DESKTOP-PIQIR88

2020-09-26 10:11:39,520 ERROR 2512 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column '${this.ctx.session.phonethis.ctx.session.phone}' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:54:5
    sql: select * from user where phone=`${this.ctx.session.phonethis.ctx.session.phone}`
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column '${this.ctx.session.phonethis.ctx.session.phone}' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "select * from user where phone=`${this.ctx.session.phonethis.ctx.session.phone}`"
name: "unhandledRejectionError"
pid: 2512
hostname: DESKTOP-K5ULKD4

2020-09-26 10:12:05,871 ERROR 13284 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column '${this.ctx.session.phone}' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:54:5
    sql: select * from user where phone=`${this.ctx.session.phone}`
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column '${this.ctx.session.phone}' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "select * from user where phone=`${this.ctx.session.phone}`"
name: "unhandledRejectionError"
pid: 13284
hostname: DESKTOP-K5ULKD4

2020-09-26 10:12:08,808 ERROR 13284 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column '${this.ctx.session.phone}' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:54:5
    sql: select * from user where phone=`${this.ctx.session.phone}`
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column '${this.ctx.session.phone}' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "select * from user where phone=`${this.ctx.session.phone}`"
name: "unhandledRejectionError"
pid: 13284
hostname: DESKTOP-K5ULKD4

2020-09-26 10:12:09,772 ERROR 13284 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column '${this.ctx.session.phone}' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:54:5
    sql: select * from user where phone=`${this.ctx.session.phone}`
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column '${this.ctx.session.phone}' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "select * from user where phone=`${this.ctx.session.phone}`"
name: "unhandledRejectionError"
pid: 13284
hostname: DESKTOP-K5ULKD4

2020-09-26 10:12:10,042 ERROR 13284 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column '${this.ctx.session.phone}' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:54:5
    sql: select * from user where phone=`${this.ctx.session.phone}`
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column '${this.ctx.session.phone}' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "select * from user where phone=`${this.ctx.session.phone}`"
name: "unhandledRejectionError"
pid: 13284
hostname: DESKTOP-K5ULKD4

2020-09-26 10:12:10,258 ERROR 13284 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column '${this.ctx.session.phone}' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:54:5
    sql: select * from user where phone=`${this.ctx.session.phone}`
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column '${this.ctx.session.phone}' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "select * from user where phone=`${this.ctx.session.phone}`"
name: "unhandledRejectionError"
pid: 13284
hostname: DESKTOP-K5ULKD4

2020-09-26 10:12:54,818 ERROR 7544 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column '"${this.ctx.session.phone}"' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:54:5
    sql: select * from user where phone=`"${this.ctx.session.phone}"`
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column '\"${this.ctx.session.phone}\"' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "select * from user where phone=`\"${this.ctx.session.phone}\"`"
name: "unhandledRejectionError"
pid: 7544
hostname: DESKTOP-K5ULKD4

2020-09-26 10:23:10,054 ERROR 2736 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column 'phone' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:54:5
    sql: select * from car where phone="1"
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'phone' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "select * from car where phone=\"1\""
name: "unhandledRejectionError"
pid: 2736
hostname: DESKTOP-K5ULKD4

2020-09-26 11:33:01,145 ERROR 7092 nodejs.ServerNoResponseError: server 127.0.0.1:53064 no response in 20001ms, maybe the socket is end on the other side. (address: 127.0.0.1:53064)
    at Timeout._onTimeout (C:\Users\12552\Desktop\mycake\cake\server\node_modules\tcp-base\lib\base.js:427:21)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ServerNoResponseError"
pid: 7092
hostname: DESKTOP-K5ULKD4

2020-09-26 11:43:21,993 ERROR 1592 nodejs.ClusterClientNoResponseError: client no response in 660841ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\12552\Desktop\mycake\cake\server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1592
hostname: DESKTOP-K5ULKD4

2020-09-26 11:43:38,828 ERROR 13232 nodejs.unhandledRejectionError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
    at Query.Sequence._packetToError (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\12552\Desktop\mycake\cake\server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:65:19)
    at C:\Users\12552\Desktop\mycake\cake\server\node_modules\co\index.js:54:5
    sql: insert into car (Uid,Gid) values ("1","25"
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1"
sqlState: "42000"
index: 0
sql: "insert into car (Uid,Gid) values (\"1\",\"25\""
name: "unhandledRejectionError"
pid: 13232
hostname: DESKTOP-K5ULKD4

2020-09-26 15:35:12,535 ERROR 1592 nodejs.ClusterClientNoResponseError: client no response in 99425ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\12552\Desktop\mycake\cake\server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 1592
hostname: DESKTOP-K5ULKD4

2020-09-26 22:53:26,756 ERROR 11732 nodejs.ClusterClientNoResponseError: client no response in 1538317ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\12552\Desktop\mycake\cake\server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 11732
hostname: DESKTOP-K5ULKD4

2020-09-26 23:35:45,872 ERROR 4328 [-/127.0.0.1/-/3ms GET /car] nodejs.TypeError: Cannot read property 'Uid' of undefined
    at CarService.car (C:\Users\12552\Desktop\mycake\cake\server\app\service\car.js:7:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async UserController.car (C:\Users\12552\Desktop\mycake\cake\server\app\controller\car.js:7:20)
    at async C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\12552\Desktop\mycake\cake\server\node_modules\koa-session\index.js:41:7)
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8081","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 4328
hostname: DESKTOP-K5ULKD4

2020-09-26 23:35:49,705 ERROR 4328 [-/127.0.0.1/-/2ms GET /car] nodejs.TypeError: Cannot read property 'Uid' of undefined
    at CarService.car (C:\Users\12552\Desktop\mycake\cake\server\app\service\car.js:7:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async UserController.car (C:\Users\12552\Desktop\mycake\cake\server\app\controller\car.js:7:20)
    at async C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\12552\Desktop\mycake\cake\server\node_modules\egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\12552\Desktop\mycake\cake\server\node_modules\koa-session\index.js:41:7)
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8081","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 4328
hostname: DESKTOP-K5ULKD4

